# Numpy Kütüphanesi

- NumPy açılımı, Numeric Python şeklindedir.
- NumPy, Python programlama diline ait bir kütüphanedir.
- Çok boyutlu dizilerle ve matrislerle çalışmamızı sağlayan ileri düzey bir kütüphanedir.
- Veri bilimi alanında çalışan kişilerin sıkça kullandığı bir kütüphanedir.

-------------------------------------------------------------------------------

Öncelikle Numpy kütüphanesini kullanmamız için kütüphane projeye dahil edilir ve projede "np" şeklinde kullanılır.

In [4]:
import numpy as np

Tek boyutlu bir dizi oluşturmak için, d adında bir dizi oluşturduk. Ve 
elemanlarını köşeli parantez içine yazdık.

In [5]:
d = np.array([5, 90, 23, 54]) 

Diziyi ekranda görmek istersek bu şekilde ekrana basabiliriz.

In [6]:
print(d)

[ 5 90 23 54]


Dizinin tipini öğrenmek istersek aşağıdaki şekilde yapabiliriz.

In [7]:
type(d)

numpy.ndarray

2 Boyutlu dizi oluşturmak için iki köşeli parantez kullanıyoruz.

In [10]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) #iki boyutlu dizi
print("İki boyutlu dizi : ", b)
print("\n Dizinin tipi : ", type(b))

İki boyutlu dizi :  [[1 2 3 4]
 [5 6 7 8]]

 Dizinin tipi :  <class 'numpy.ndarray'>


Dizinin satır ve sütun sayısını öğrenmek istersek "shape" komutunu kullanırız.


In [11]:
np.shape(b) # (x, y) x, satır sayısını ve y, sütun sayısını verir.

(2, 4)

Şimdi reshape komutu ile a dizisini istediğimiz satır ve sütun sayısına çevirelim.

In [12]:
a = np.array([1,2,3,4,5,6,7,8,9])

c = a.reshape(3,3)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Şimdi np.arange() komutuna bakalım. arange komutu 4 parametre alır;
np.arange(başlangıç değeri, bitiş değeri, değişim miktarı, veri tipi)

In [41]:
dizi1 = np.arange(0,250,8)

np.arange(), sadece tek boyutlu dizi oluştursa da, reshape komutunu kullanarak dizimizi iki boyutlu hale getirebiliriz.

In [42]:
dizi1

array([  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96,
       104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200,
       208, 216, 224, 232, 240, 248])

np.linspace(), komutu ile iki değer arasında kaç sayı olması gerektiğini söyleriz. 3 parametre alır; dizinin başlangıç değeri, bitiş değeri ve bu aralıktaki kaç değer alması gerektiğidir.

In [43]:
dizi2 = np.linspace(1,5,10)

In [44]:
dizi2

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

np.zeros(), sıfırlardan oluşan bir matris elde etmemizi sağlar.
np.zeros((4,4)) satır sütun sayısının parametrelerini alır. 

In [45]:
dizi3 = np.zeros((5,5))
dizi3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

np.ones(), komutu birlerden oluşan bir matris elde etmemizi sağlar.

In [46]:
dizi4 = np.ones((3,3))
dizi4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

np.full() komutu iki parametre alır, ilki satır ve sütun sayısı ikincisi matirisin hangi sayıdan oluşağıdır.

In [47]:
dizi5 = np.full((4,5),9)
dizi5

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

np.random() istenilen boyutta bir dizin oluşturur ve içerisini 0-1 aralığında ki sayıalarla doldurur.

In [48]:
dizi6 = np.random.random((3,4))
dizi6

array([[0.55122384, 0.54390477, 0.94103162, 0.47934043],
       [0.88751023, 0.14497717, 0.19268263, 0.30777366],
       [0.4613736 , 0.93271201, 0.08506206, 0.61610389]])

np.eye() komutu.

In [49]:
dizi7 = np.eye(9)
dizi7

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [51]:
dizi8 = np.random.random((3,6))

In [54]:
dizi8.shape # dizinin satır ve sütun sayısı

(3, 6)

In [57]:
dizi8.ndim # dizinin boyutunu öğrenmek için

2

In [58]:
dizi8.size # dizinin eleman sayısı

18

In [59]:
dizi8.dtype #dizinin veri tipini öğrenmek için

dtype('float64')